name: simplex-chat
version: 0.3.1
#synopsis:
#description:
homepage: https://github.com/simplex-chat/simplex-chat#readme
license: AGPL-3
author: Evgeny Poberezkin
maintainer: evgeny@poberezkin.com
copyright: 2020 Evgeny Poberezkin
category: Web, System, Services, Cryptography
extra-source-files:
  - README.md

dependencies:
  - ansi-terminal == 0.10.*
  - attoparsec == 0.13.*
  - base >= 4.7 && < 5
  - bytestring == 0.10.*
  - containers == 0.6.*
  - simplexmq == 0.3.*
  - text == 1.2.*

library:
  source-dirs: src

executables:
  simplex-chat:
    source-dirs: apps/simplex-chat
    main: Main.hs
    dependencies:
      - simplex-chat
      - async == 2.2.*
      - bytestring == 0.10.*
      - composition == 1.0.*
      - directory == 1.3.*
      - file-embed == 0.0.14.*
      - filepath == 1.4.*
      - mtl == 2.2.*
      - optparse-applicative == 0.15.*
      - process == 1.6.*
      - simple-logger == 0.1.*
      - simplexmq == 0.3.*
      - sqlite-simple == 0.4.*
      - stm == 2.5.*
      - terminal == 0.2.*
      - time == 1.9.*
      - unliftio == 0.2.*
      - unliftio-core == 0.2.*
    ghc-options:
      - -threaded

tests:
  simplex-chat-test:
    source-dirs: tests
    main: Test.hs
    dependencies:
      - simplex-chat
      - hspec == 2.7.*

ghc-options:
  # - -haddock
  - -Wall
  - -Wcompat
  - -Werror=incomplete-patterns
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wunused-type-patterns
